module.exports = {
  pieces:[
   { 'piece': 'rook', 'owner': 1, 'x': 0, 'y': 0 },
   { 'piece': 'knight', 'owner': 1, 'x': 1, 'y': 0 },
   { 'piece': 'bishop', 'owner': 1, 'x': 2, 'y': 0 },
   { 'piece': 'queen', 'owner': 1, 'x': 3, 'y': 0 },
   { 'piece': 'king', 'owner': 1, 'x': 4, 'y': 0 },
   { 'piece': 'bishop', 'owner': 1, 'x': 5, 'y': 0 },
   { 'piece': 'knight', 'owner': 1, 'x': 6, 'y': 0 },
   { 'piece': 'rook', 'owner': 1, 'x': 7, 'y': 0 },
   { 'piece': 'pawn', 'owner': 1, 'x': 0, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 1, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 2, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 3, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 4, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 5, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 6, 'y': 1 },
   { 'piece': 'pawn', 'owner': 1, 'x': 7, 'y': 1 },
   { 'piece': 'pawn', 'owner': 0, 'x': 0, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 1, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 2, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 3, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 4, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 5, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 6, 'y': 6 },
   { 'piece': 'pawn', 'owner': 0, 'x': 7, 'y': 6 },
   { 'piece': 'rook', 'owner': 0, 'x': 0, 'y': 7 },
   { 'piece': 'knight', 'owner': 0, 'x': 1, 'y': 7 },
   { 'piece': 'bishop', 'owner': 0, 'x': 2, 'y': 7 },
   { 'piece': 'queen', 'owner': 0, 'x': 3, 'y': 7 },
   { 'piece': 'king', 'owner': 0, 'x': 4, 'y': 7 },
   { 'piece': 'bishop', 'owner': 0, 'x': 5, 'y': 7 },
   { 'piece': 'knight', 'owner': 0, 'x': 6, 'y': 7 },
   { 'piece': 'rook', 'owner': 0, 'x': 7, 'y': 7 },
   { 'piece': 'testRook', 'owner': 0, 'x': 4, 'y': 4 }
]
}
