  let pieces=[
   { 'piece': 'rook', 'owner': 1, 'x': 0, 'y': 7, 'char': '♜' },
   { 'piece': 'knight', 'owner': 1, 'x': 1, 'y': 7, 'char': '♞'},
   { 'piece': 'bishop', 'owner': 1, 'x': 2, 'y': 7, 'char': '♝' },
   { 'piece': 'queen', 'owner': 1, 'x': 4, 'y': 7, 'char': '♛' },
   { 'piece': 'king', 'owner': 1, 'x': 3, 'y': 7, 'char': '♚' },
   { 'piece': 'bishop', 'owner': 1, 'x': 5, 'y': 7, 'char': '♝' },
   { 'piece': 'knight', 'owner': 1, 'x': 6, 'y': 7, 'char': '♞' },
   { 'piece': 'rook', 'owner': 1, 'x': 7, 'y': 7, 'char': '♜' },
   { 'piece': 'pawn', 'owner': 1, 'x': 0, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 1, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 2, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 3, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 4, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 5, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 6, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 1, 'x': 7, 'y': 6, 'char': '♟'},
   { 'piece': 'pawn', 'owner': 0, 'x': 0, 'y': 1, 'char':'♙' },
   { 'piece': 'pawn', 'owner': 0, 'x': 1, 'y': 1, 'char':'♙' },
   { 'piece': 'pawn', 'owner': 0, 'x': 2, 'y': 1, 'char':'♙' },
   { 'piece': 'pawn', 'owner': 0, 'x': 3, 'y': 1, 'char':'♙' },
   { 'piece': 'pawn', 'owner': 0, 'x': 4, 'y': 1, 'char':'♙' },
   { 'piece': 'pawn', 'owner': 0, 'x': 5, 'y': 1, 'char':'♙' },
   { 'piece': 'pawn', 'owner': 0, 'x': 6, 'y': 1, 'char':'♙'},
   { 'piece': 'pawn', 'owner': 0, 'x': 7, 'y': 1, 'char':'♙' },
   { 'piece': 'rook', 'owner': 0, 'x': 0, 'y': 0, 'char':'♖'},
   { 'piece': 'knight', 'owner': 0, 'x': 1, 'y': 0, 'char':'♘' },
   { 'piece': 'bishop', 'owner': 0, 'x': 2, 'y': 0, 'char': '♗'},
   { 'piece': 'queen', 'owner': 0, 'x': 4, 'y': 0, 'char':'♕ '},
   { 'piece': 'king', 'owner': 0, 'x': 3, 'y': 0, 'char':'♔'},
   { 'piece': 'bishop', 'owner': 0, 'x': 5, 'y': 0, 'char': '♗'},
   { 'piece': 'knight', 'owner': 0, 'x': 6, 'y': 0, 'char': '♘'},
   { 'piece': 'rook', 'owner': 0, 'x': 7, 'y': 0, 'char':'♖'}
]
