module.exports = [
  {pieces: [
  {"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
  {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
  {"piece": "bishop", "owner": 1, "x": 2, "y": 7, "char": "♝", "id": "f8"},
  {"piece": "queen", "owner": 1, "x": 4, "y": 7, "char": "♛", "id": "d8"},
  {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
  {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
  {"piece": "knight", "owner": 1, "x": 6, "y": 7, "char": "♞", "id": "b8"},
  {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
  {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
  {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
  {"piece": "pawn", "owner": 1, "x": 2, "y": 6, "char": "♟", "id": "f7"},
  {"piece": "pawn", "owner": 1, "x": 3, "y": 6, "char": "♟", "id": "e7"},
  {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
  {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
  {"piece": "pawn", "owner": 1, "x": 6, "y": 6, "char": "♟", "id": "b7"},
  {"piece": "pawn", "owner": 1, "x": 7, "y": 6, "char": "♟", "id": "a7"},
  {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
  {"piece": "pawn", "owner": 0, "x": 1, "y": 1, "char": "♙", "id": "g2"},
  {"piece": "pawn", "owner": 0, "x": 2, "y": 1, "char": "♙", "id": "f2"},
  {"piece": "pawn", "owner": 0, "x": 3, "y": 1, "char": "♙", "id": "e2"},
  {"piece": "pawn", "owner": 0, "x": 4, "y": 1, "char": "♙", "id": "d2"},
  {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
  {"piece": "pawn", "owner": 0, "x": 6, "y": 1, "char": "♙", "id": "b2"},
  {"piece": "pawn", "owner": 0, "x": 7, "y": 1, "char": "♙", "id": "a2"},
  {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
  {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
  {"piece": "bishop", "owner": 0, "x": 2, "y": 0, "char": "♗", "id": "f1"},
  {"piece": "queen", "owner": 0, "x": 4, "y": 0, "char": "♕ ", "id": "d1"},
  {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
  {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
  {"piece": "knight", "owner": 0, "x": 6, "y": 0, "char": "♘", "id": "b1"},
  {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}],
    player:0,
    'check?': false,
    'mate?': false},

  { pieces: [
  {"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
  {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
  {"piece": "bishop", "owner": 1, "x": 2, "y": 7, "char": "♝", "id": "f8"},
  {"piece": "queen", "owner": 1, "x": 4, "y": 7, "char": "♛", "id": "d8"},
  {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
  {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
  {"piece": "knight", "owner": 1, "x": 6, "y": 7, "char": "♞", "id": "b8"},
  {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
  {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
  {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
  {"piece": "pawn", "owner": 1, "x": 2, "y": 6, "char": "♟", "id": "f7"},
  {"piece": "pawn", "owner": 1, "x": 3, "y": 6, "char": "♟", "id": "e7"},
  {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
  {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
  {"piece": "pawn", "owner": 1, "x": 6, "y": 6, "char": "♟", "id": "b7"},
  {"piece": "pawn", "owner": 1, "x": 7, "y": 6, "char": "♟", "id": "a7"},
  {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
  {"piece": "pawn", "owner": 0, "x": 1, "y": 1, "char": "♙", "id": "g2"},
  {"piece": "pawn", "owner": 0, "x": 2, "y": 1, "char": "♙", "id": "f2"},
  {"piece": "pawn", "owner": 0, "x": 3, "y": 1, "char": "♙", "id": "e2"},
  {"piece": "pawn", "owner": 0, "x": 4, "y": 2, "char": "♙", "id": "d3"},
  {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
  {"piece": "pawn", "owner": 0, "x": 6, "y": 1, "char": "♙", "id": "b2"},
  {"piece": "pawn", "owner": 0, "x": 7, "y": 1, "char": "♙", "id": "a2"},
  {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
  {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
  {"piece": "bishop", "owner": 0, "x": 2, "y": 0, "char": "♗", "id": "f1"},
  {"piece": "queen", "owner": 0, "x": 4, "y": 0, "char": "♕ ", "id": "d1"},
  {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
  {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
  {"piece": "knight", "owner": 0, "x": 6, "y": 0, "char": "♘", "id": "b1"},
  {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}], 
  player: 1,
  'check?': false,
  'mate?': false
  },

  {pieces:
  [{"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
 {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
 {"piece": "bishop", "owner": 1, "x": 2, "y": 7, "char": "♝", "id": "f8"},
 {"piece": "queen", "owner": 1, "x": 4, "y": 7, "char": "♛", "id": "d8"},
 {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
 {"piece": "knight", "owner": 1, "x": 6, "y": 7, "char": "♞", "id": "b8"},
 {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
 {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
 {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
 {"piece": "pawn", "owner": 1, "x": 2, "y": 6, "char": "♟", "id": "f7"},
 {"piece": "pawn", "owner": 1, "x": 3, "y": 6, "char": "♟", "id": "e7"},
 {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
 {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
 {"piece": "pawn", "owner": 1, "x": 6, "y": 6, "char": "♟", "id": "b7"},
 {"piece": "pawn", "owner": 1, "x": 7, "y": 5, "char": "♟", "id": "a6"},
 {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
 {"piece": "pawn", "owner": 0, "x": 1, "y": 1, "char": "♙", "id": "g2"},
 {"piece": "pawn", "owner": 0, "x": 2, "y": 1, "char": "♙", "id": "f2"},
 {"piece": "pawn", "owner": 0, "x": 3, "y": 2, "char": "♙", "id": "e3"},
 {"piece": "pawn", "owner": 0, "x": 4, "y": 1, "char": "♙", "id": "d2"},
 {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
 {"piece": "pawn", "owner": 0, "x": 6, "y": 1, "char": "♙", "id": "b2"},
 {"piece": "pawn", "owner": 0, "x": 7, "y": 1, "char": "♙", "id": "a2"},
 {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
 {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
 {"piece": "bishop", "owner": 0, "x": 2, "y": 0, "char": "♗", "id": "f1"},
 {"piece": "queen", "owner": 0, "x": 4, "y": 0, "char": "♕ ", "id": "d1"},
 {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
 {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
 {"piece": "knight", "owner": 0, "x": 6, "y": 0, "char": "♘", "id": "b1"},
 {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}],
  player: 1,
  'check?': false,
  'mate?': false
 },

 {pieces:
 [{"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
 {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
 {"piece": "bishop", "owner": 1, "x": 2, "y": 7, "char": "♝", "id": "f8"},
 {"piece": "queen", "owner": 1, "x": 4, "y": 7, "char": "♛", "id": "d8"},
 {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
 {"piece": "knight", "owner": 1, "x": 6, "y": 7, "char": "♞", "id": "b8"},
 {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
 {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
 {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
 {"piece": "pawn", "owner": 1, "x": 2, "y": 5, "char": "♟", "id": "f6"},
 {"piece": "pawn", "owner": 1, "x": 3, "y": 6, "char": "♟", "id": "e7"},
 {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
 {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
 {"piece": "pawn", "owner": 1, "x": 6, "y": 6, "char": "♟", "id": "b7"},
 {"piece": "pawn", "owner": 1, "x": 7, "y": 6, "char": "♟", "id": "a7"},
 {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
 {"piece": "pawn", "owner": 0, "x": 1, "y": 1, "char": "♙", "id": "g2"},
 {"piece": "pawn", "owner": 0, "x": 2, "y": 1, "char": "♙", "id": "f2"},
 {"piece": "pawn", "owner": 0, "x": 3, "y": 2, "char": "♙", "id": "e3"},
 {"piece": "pawn", "owner": 0, "x": 4, "y": 1, "char": "♙", "id": "d2"},
 {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
 {"piece": "pawn", "owner": 0, "x": 6, "y": 1, "char": "♙", "id": "b2"},
 {"piece": "pawn", "owner": 0, "x": 7, "y": 1, "char": "♙", "id": "a2"},
 {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
 {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
 {"piece": "bishop", "owner": 0, "x": 2, "y": 0, "char": "♗", "id": "f1"},
 {"piece": "queen", "owner": 0, "x": 0, "y": 4, "char": "♕ ", "id": "h5"},
 {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
 {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
 {"piece": "knight", "owner": 0, "x": 6, "y": 0, "char": "♘", "id": "b1"},
 {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}],
   player: 1,
   'check?': true,
   'mate?': false
 },

 {pieces:
 [{"piece": "queen", "owner": 0, "x": 2, "y": 6, "char": "♕ ", "id": "f7"},
 {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
 {"piece": "pawn", "owner": 1, "x": 7, "y": 5, "char": "♟", "id": "a6"},
 {"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
 {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
 {"piece": "bishop", "owner": 1, "x": 2, "y": 7, "char": "♝", "id": "f8"},
 {"piece": "queen", "owner": 1, "x": 4, "y": 7, "char": "♛", "id": "d8"},
 {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
 {"piece": "knight", "owner": 1, "x": 5, "y": 5, "char": "♞", "id": "c6"},
 {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
 {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
 {"piece": "pawn", "owner": 1, "x": 3, "y": 6, "char": "♟", "id": "e7"},
 {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
 {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
 {"piece": "pawn", "owner": 1, "x": 6, "y": 5, "char": "♟", "id": "b6"},
 {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
 {"piece": "pawn", "owner": 0, "x": 1, "y": 1, "char": "♙", "id": "g2"},
 {"piece": "pawn", "owner": 0, "x": 2, "y": 1, "char": "♙", "id": "f2"},
 {"piece": "pawn", "owner": 0, "x": 3, "y": 2, "char": "♙", "id": "e3"},
 {"piece": "pawn", "owner": 0, "x": 4, "y": 1, "char": "♙", "id": "d2"},
 {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
 {"piece": "pawn", "owner": 0, "x": 6, "y": 1, "char": "♙", "id": "b2"},
 {"piece": "pawn", "owner": 0, "x": 7, "y": 1, "char": "♙", "id": "a2"},
 {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
 {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
 {"piece": "bishop", "owner": 0, "x": 5, "y": 3, "char": "♗", "id": "c4"},
 {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
 {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
 {"piece": "knight", "owner": 0, "x": 6, "y": 0, "char": "♘", "id": "b1"},
 {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}],
   player: 1,
   'check?': true,
   'mate?': true 
 },
 {pieces: 
 [{"piece": "pawn", "owner": 0, "x": 7, "y": 2, "char": "♙", "id": "a3"},
 {"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
 {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 4, "char": "♝", "id": "c5"},
 {"piece": "queen", "owner": 1, "x": 0, "y": 3, "char": "♛", "id": "h4"},
 {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
 {"piece": "knight", "owner": 1, "x": 6, "y": 7, "char": "♞", "id": "b8"},
 {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
 {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
 {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
 {"piece": "pawn", "owner": 1, "x": 2, "y": 6, "char": "♟", "id": "f7"},
 {"piece": "pawn", "owner": 1, "x": 3, "y": 5, "char": "♟", "id": "e6"},
 {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
 {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
 {"piece": "pawn", "owner": 1, "x": 6, "y": 6, "char": "♟", "id": "b7"},
 {"piece": "pawn", "owner": 1, "x": 7, "y": 5, "char": "♟", "id": "a6"},
 {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
 {"piece": "pawn", "owner": 0, "x": 1, "y": 1, "char": "♙", "id": "g2"},
 {"piece": "pawn", "owner": 0, "x": 2, "y": 2, "char": "♙", "id": "f3"},
 {"piece": "pawn", "owner": 0, "x": 3, "y": 1, "char": "♙", "id": "e2"},
 {"piece": "pawn", "owner": 0, "x": 4, "y": 1, "char": "♙", "id": "d2"},
 {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
 {"piece": "pawn", "owner": 0, "x": 6, "y": 2, "char": "♙", "id": "b3"},
 {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
 {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
 {"piece": "bishop", "owner": 0, "x": 2, "y": 0, "char": "♗", "id": "f1"},
 {"piece": "queen", "owner": 0, "x": 4, "y": 0, "char": "♕ ", "id": "d1"},
 {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
 {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
 {"piece": "knight", "owner": 0, "x": 5, "y": 2, "char": "♘", "id": "c3"},
 {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}],
   player: 0,
   'check?':true,
   'mate?': false
  },

 {pieces:
 [{"piece": "queen", "owner": 1, "x": 2, "y": 1, "char": "♛", "id": "f2"},
 {"piece": "knight", "owner": 0, "x": 5, "y": 2, "char": "♘", "id": "c3"},
 {"piece": "knight", "owner": 0, "x": 1, "y": 0, "char": "♘", "id": "g1"},
 {"piece": "pawn", "owner": 0, "x": 4, "y": 1, "char": "♙", "id": "d2"},
 {"piece": "pawn", "owner": 0, "x": 7, "y": 3, "char": "♙", "id": "a4"},
 {"piece": "pawn", "owner": 0, "x": 1, "y": 2, "char": "♙", "id": "g3"},
 {"piece": "pawn", "owner": 0, "x": 0, "y": 1, "char": "♙", "id": "h2"},
 {"piece": "rook", "owner": 1, "x": 0, "y": 7, "char": "♜", "id": "h8"},
 {"piece": "knight", "owner": 1, "x": 1, "y": 7, "char": "♞", "id": "g8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 4, "char": "♝", "id": "c5"},
 {"piece": "king", "owner": 1, "x": 3, "y": 7, "char": "♚", "id": "e8"},
 {"piece": "bishop", "owner": 1, "x": 5, "y": 7, "char": "♝", "id": "c8"},
 {"piece": "knight", "owner": 1, "x": 6, "y": 7, "char": "♞", "id": "b8"},
 {"piece": "rook", "owner": 1, "x": 7, "y": 7, "char": "♜", "id": "a8"},
 {"piece": "pawn", "owner": 1, "x": 0, "y": 6, "char": "♟", "id": "h7"},
 {"piece": "pawn", "owner": 1, "x": 1, "y": 6, "char": "♟", "id": "g7"},
 {"piece": "pawn", "owner": 1, "x": 2, "y": 6, "char": "♟", "id": "f7"},
 {"piece": "pawn", "owner": 1, "x": 3, "y": 5, "char": "♟", "id": "e6"},
 {"piece": "pawn", "owner": 1, "x": 4, "y": 6, "char": "♟", "id": "d7"},
 {"piece": "pawn", "owner": 1, "x": 5, "y": 6, "char": "♟", "id": "c7"},
 {"piece": "pawn", "owner": 1, "x": 6, "y": 6, "char": "♟", "id": "b7"},
 {"piece": "pawn", "owner": 1, "x": 7, "y": 5, "char": "♟", "id": "a6"},
 {"piece": "pawn", "owner": 0, "x": 2, "y": 2, "char": "♙", "id": "f3"},
 {"piece": "pawn", "owner": 0, "x": 3, "y": 1, "char": "♙", "id": "e2"},
 {"piece": "pawn", "owner": 0, "x": 5, "y": 1, "char": "♙", "id": "c2"},
 {"piece": "pawn", "owner": 0, "x": 6, "y": 2, "char": "♙", "id": "b3"},
 {"piece": "rook", "owner": 0, "x": 0, "y": 0, "char": "♖", "id": "h1"},
 {"piece": "bishop", "owner": 0, "x": 2, "y": 0, "char": "♗", "id": "f1"},
 {"piece": "queen", "owner": 0, "x": 4, "y": 0, "char": "♕ ", "id": "d1"},
 {"piece": "king", "owner": 0, "x": 3, "y": 0, "char": "♔", "id": "e1"},
 {"piece": "bishop", "owner": 0, "x": 5, "y": 0, "char": "♗", "id": "c1"},
 {"piece": "rook", "owner": 0, "x": 7, "y": 0, "char": "♖", "id": "a1"}],
  player: 0,
  'check?':true,
  'mate?': true
}

]

